name: "Pull Request Semantic and Label Verification"

on: [pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Validate pull request title semantic
        uses: amannn/action-semantic-pull-request@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add labels based on pull request title
        uses: TDAK1509/set-label-based-on-pr-title@v1.1
        with:
          words: feat;bug
          labels: 'Type: Enhancement'; 'Type: Bug'
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
